/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing AdditionalAdvancedScanInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AdditionalAdvancedScanInformationTests
    {
        // TODO uncomment below to declare an instance variable for AdditionalAdvancedScanInformation
        //private AdditionalAdvancedScanInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AdditionalAdvancedScanInformation
            //instance = new AdditionalAdvancedScanInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdditionalAdvancedScanInformation
        /// </summary>
        [Test]
        public void AdditionalAdvancedScanInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdditionalAdvancedScanInformation
            //Assert.IsInstanceOfType<AdditionalAdvancedScanInformation> (instance, "variable 'instance' is a AdditionalAdvancedScanInformation");
        }


        /// <summary>
        /// Test the property 'ContainsJSON'
        /// </summary>
        [Test]
        public void ContainsJSONTest()
        {
            // TODO unit test for the property 'ContainsJSON'
        }
        /// <summary>
        /// Test the property 'ContainsXML'
        /// </summary>
        [Test]
        public void ContainsXMLTest()
        {
            // TODO unit test for the property 'ContainsXML'
        }
        /// <summary>
        /// Test the property 'ContainsImage'
        /// </summary>
        [Test]
        public void ContainsImageTest()
        {
            // TODO unit test for the property 'ContainsImage'
        }
        /// <summary>
        /// Test the property 'RelevantSubfileName'
        /// </summary>
        [Test]
        public void RelevantSubfileNameTest()
        {
            // TODO unit test for the property 'RelevantSubfileName'
        }

    }

}
