/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Model
{
    /// <summary>
    ///  Class for testing CloudStorageVirusScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloudStorageVirusScanResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloudStorageVirusScanResult
        //private CloudStorageVirusScanResult instance;

        public CloudStorageVirusScanResultTests()
        {
            // TODO uncomment below to create an instance of CloudStorageVirusScanResult
            //instance = new CloudStorageVirusScanResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloudStorageVirusScanResult
        /// </summary>
        [Fact]
        public void CloudStorageVirusScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloudStorageVirusScanResult
            //Assert.IsType<CloudStorageVirusScanResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Fact]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }

        /// <summary>
        /// Test the property 'ErrorDetailedDescription'
        /// </summary>
        [Fact]
        public void ErrorDetailedDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDetailedDescription'
        }

        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Fact]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }

        /// <summary>
        /// Test the property 'ContainsContentModerationRejection'
        /// </summary>
        [Fact]
        public void ContainsContentModerationRejectionTest()
        {
            // TODO unit test for the property 'ContainsContentModerationRejection'
        }

        /// <summary>
        /// Test the property 'ContainsExecutable'
        /// </summary>
        [Fact]
        public void ContainsExecutableTest()
        {
            // TODO unit test for the property 'ContainsExecutable'
        }

        /// <summary>
        /// Test the property 'ContainsInvalidFile'
        /// </summary>
        [Fact]
        public void ContainsInvalidFileTest()
        {
            // TODO unit test for the property 'ContainsInvalidFile'
        }

        /// <summary>
        /// Test the property 'ContainsScript'
        /// </summary>
        [Fact]
        public void ContainsScriptTest()
        {
            // TODO unit test for the property 'ContainsScript'
        }

        /// <summary>
        /// Test the property 'ContainsPasswordProtectedFile'
        /// </summary>
        [Fact]
        public void ContainsPasswordProtectedFileTest()
        {
            // TODO unit test for the property 'ContainsPasswordProtectedFile'
        }

        /// <summary>
        /// Test the property 'ContainsRestrictedFileFormat'
        /// </summary>
        [Fact]
        public void ContainsRestrictedFileFormatTest()
        {
            // TODO unit test for the property 'ContainsRestrictedFileFormat'
        }

        /// <summary>
        /// Test the property 'ContainsMacros'
        /// </summary>
        [Fact]
        public void ContainsMacrosTest()
        {
            // TODO unit test for the property 'ContainsMacros'
        }

        /// <summary>
        /// Test the property 'ContainsXmlExternalEntities'
        /// </summary>
        [Fact]
        public void ContainsXmlExternalEntitiesTest()
        {
            // TODO unit test for the property 'ContainsXmlExternalEntities'
        }

        /// <summary>
        /// Test the property 'ContainsInsecureDeserialization'
        /// </summary>
        [Fact]
        public void ContainsInsecureDeserializationTest()
        {
            // TODO unit test for the property 'ContainsInsecureDeserialization'
        }

        /// <summary>
        /// Test the property 'ContainsHtml'
        /// </summary>
        [Fact]
        public void ContainsHtmlTest()
        {
            // TODO unit test for the property 'ContainsHtml'
        }

        /// <summary>
        /// Test the property 'ContainsUnsafeArchive'
        /// </summary>
        [Fact]
        public void ContainsUnsafeArchiveTest()
        {
            // TODO unit test for the property 'ContainsUnsafeArchive'
        }

        /// <summary>
        /// Test the property 'ContainsOleEmbeddedObject'
        /// </summary>
        [Fact]
        public void ContainsOleEmbeddedObjectTest()
        {
            // TODO unit test for the property 'ContainsOleEmbeddedObject'
        }

        /// <summary>
        /// Test the property 'VerifiedFileFormat'
        /// </summary>
        [Fact]
        public void VerifiedFileFormatTest()
        {
            // TODO unit test for the property 'VerifiedFileFormat'
        }
    }
}
