/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing CloudStorageVirusFound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CloudStorageVirusFoundTests
    {
        // TODO uncomment below to declare an instance variable for CloudStorageVirusFound
        //private CloudStorageVirusFound instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CloudStorageVirusFound
            //instance = new CloudStorageVirusFound();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CloudStorageVirusFound
        /// </summary>
        [Test]
        public void CloudStorageVirusFoundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CloudStorageVirusFound
            //Assert.IsInstanceOfType<CloudStorageVirusFound> (instance, "variable 'instance' is a CloudStorageVirusFound");
        }


        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'VirusName'
        /// </summary>
        [Test]
        public void VirusNameTest()
        {
            // TODO unit test for the property 'VirusName'
        }

    }

}
