/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing CloudStorageVirusScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CloudStorageVirusScanResultTests
    {
        // TODO uncomment below to declare an instance variable for CloudStorageVirusScanResult
        //private CloudStorageVirusScanResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CloudStorageVirusScanResult
            //instance = new CloudStorageVirusScanResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CloudStorageVirusScanResult
        /// </summary>
        [Test]
        public void CloudStorageVirusScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CloudStorageVirusScanResult
            //Assert.IsInstanceOfType<CloudStorageVirusScanResult> (instance, "variable 'instance' is a CloudStorageVirusScanResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Test]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }
        /// <summary>
        /// Test the property 'ErrorDetailedDescription'
        /// </summary>
        [Test]
        public void ErrorDetailedDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDetailedDescription'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Test]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'ContainsContentModerationRejection'
        /// </summary>
        [Test]
        public void ContainsContentModerationRejectionTest()
        {
            // TODO unit test for the property 'ContainsContentModerationRejection'
        }

    }

}
