/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing ScanCloudStorageBatchJobCreateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScanCloudStorageBatchJobCreateResultTests
    {
        // TODO uncomment below to declare an instance variable for ScanCloudStorageBatchJobCreateResult
        //private ScanCloudStorageBatchJobCreateResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScanCloudStorageBatchJobCreateResult
            //instance = new ScanCloudStorageBatchJobCreateResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScanCloudStorageBatchJobCreateResult
        /// </summary>
        [Test]
        public void ScanCloudStorageBatchJobCreateResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScanCloudStorageBatchJobCreateResult
            //Assert.IsInstanceOfType<ScanCloudStorageBatchJobCreateResult> (instance, "variable 'instance' is a ScanCloudStorageBatchJobCreateResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Test]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }

    }

}
