/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing ScanCloudStorageJobStatusResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScanCloudStorageJobStatusResultTests
    {
        // TODO uncomment below to declare an instance variable for ScanCloudStorageJobStatusResult
        //private ScanCloudStorageJobStatusResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScanCloudStorageJobStatusResult
            //instance = new ScanCloudStorageJobStatusResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScanCloudStorageJobStatusResult
        /// </summary>
        [Test]
        public void ScanCloudStorageJobStatusResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScanCloudStorageJobStatusResult
            //Assert.IsInstanceOfType<ScanCloudStorageJobStatusResult> (instance, "variable 'instance' is a ScanCloudStorageJobStatusResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'AsyncJobStatus'
        /// </summary>
        [Test]
        public void AsyncJobStatusTest()
        {
            // TODO unit test for the property 'AsyncJobStatus'
        }
        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Test]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'JobDuration'
        /// </summary>
        [Test]
        public void JobDurationTest()
        {
            // TODO unit test for the property 'JobDuration'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
