/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Model
{
    /// <summary>
    ///  Class for testing ScanCloudStorageJobStatusResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScanCloudStorageJobStatusResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScanCloudStorageJobStatusResult
        //private ScanCloudStorageJobStatusResult instance;

        public ScanCloudStorageJobStatusResultTests()
        {
            // TODO uncomment below to create an instance of ScanCloudStorageJobStatusResult
            //instance = new ScanCloudStorageJobStatusResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanCloudStorageJobStatusResult
        /// </summary>
        [Fact]
        public void ScanCloudStorageJobStatusResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScanCloudStorageJobStatusResult
            //Assert.IsType<ScanCloudStorageJobStatusResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'AsyncJobStatus'
        /// </summary>
        [Fact]
        public void AsyncJobStatusTest()
        {
            // TODO unit test for the property 'AsyncJobStatus'
        }

        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Fact]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

        /// <summary>
        /// Test the property 'JobDuration'
        /// </summary>
        [Fact]
        public void JobDurationTest()
        {
            // TODO unit test for the property 'JobDuration'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
