/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Model
{
    /// <summary>
    ///  Class for testing ScanCloudStorageBatchJobCreateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScanCloudStorageBatchJobCreateResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScanCloudStorageBatchJobCreateResult
        //private ScanCloudStorageBatchJobCreateResult instance;

        public ScanCloudStorageBatchJobCreateResultTests()
        {
            // TODO uncomment below to create an instance of ScanCloudStorageBatchJobCreateResult
            //instance = new ScanCloudStorageBatchJobCreateResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanCloudStorageBatchJobCreateResult
        /// </summary>
        [Fact]
        public void ScanCloudStorageBatchJobCreateResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScanCloudStorageBatchJobCreateResult
            //Assert.IsType<ScanCloudStorageBatchJobCreateResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Fact]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }
    }
}
