/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Model
{
    /// <summary>
    ///  Class for testing VirusFound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirusFoundTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirusFound
        //private VirusFound instance;

        public VirusFoundTests()
        {
            // TODO uncomment below to create an instance of VirusFound
            //instance = new VirusFound();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirusFound
        /// </summary>
        [Fact]
        public void VirusFoundInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirusFound
            //Assert.IsType<VirusFound>(instance);
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

        /// <summary>
        /// Test the property 'VirusName'
        /// </summary>
        [Fact]
        public void VirusNameTest()
        {
            // TODO unit test for the property 'VirusName'
        }
    }
}
