/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Model
{
    /// <summary>
    ///  Class for testing VirusScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirusScanResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirusScanResult
        //private VirusScanResult instance;

        public VirusScanResultTests()
        {
            // TODO uncomment below to create an instance of VirusScanResult
            //instance = new VirusScanResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirusScanResult
        /// </summary>
        [Fact]
        public void VirusScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirusScanResult
            //Assert.IsType<VirusScanResult>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Fact]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }
    }
}
