/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing VirusScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VirusScanResultTests
    {
        // TODO uncomment below to declare an instance variable for VirusScanResult
        //private VirusScanResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VirusScanResult
            //instance = new VirusScanResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VirusScanResult
        /// </summary>
        [Test]
        public void VirusScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VirusScanResult
            //Assert.IsInstanceOfType<VirusScanResult> (instance, "variable 'instance' is a VirusScanResult");
        }


        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Test]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }

    }

}
