/* 
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing VirusScanAdvancedResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VirusScanAdvancedResultTests
    {
        // TODO uncomment below to declare an instance variable for VirusScanAdvancedResult
        //private VirusScanAdvancedResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VirusScanAdvancedResult
            //instance = new VirusScanAdvancedResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VirusScanAdvancedResult
        /// </summary>
        [Test]
        public void VirusScanAdvancedResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VirusScanAdvancedResult
            //Assert.IsInstanceOfType<VirusScanAdvancedResult> (instance, "variable 'instance' is a VirusScanAdvancedResult");
        }


        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'ContainsExecutable'
        /// </summary>
        [Test]
        public void ContainsExecutableTest()
        {
            // TODO unit test for the property 'ContainsExecutable'
        }
        /// <summary>
        /// Test the property 'ContainsInvalidFile'
        /// </summary>
        [Test]
        public void ContainsInvalidFileTest()
        {
            // TODO unit test for the property 'ContainsInvalidFile'
        }
        /// <summary>
        /// Test the property 'ContainsScript'
        /// </summary>
        [Test]
        public void ContainsScriptTest()
        {
            // TODO unit test for the property 'ContainsScript'
        }
        /// <summary>
        /// Test the property 'ContainsPasswordProtectedFile'
        /// </summary>
        [Test]
        public void ContainsPasswordProtectedFileTest()
        {
            // TODO unit test for the property 'ContainsPasswordProtectedFile'
        }
        /// <summary>
        /// Test the property 'ContainsRestrictedFileFormat'
        /// </summary>
        [Test]
        public void ContainsRestrictedFileFormatTest()
        {
            // TODO unit test for the property 'ContainsRestrictedFileFormat'
        }
        /// <summary>
        /// Test the property 'ContainsMacros'
        /// </summary>
        [Test]
        public void ContainsMacrosTest()
        {
            // TODO unit test for the property 'ContainsMacros'
        }
        /// <summary>
        /// Test the property 'ContainsXmlExternalEntities'
        /// </summary>
        [Test]
        public void ContainsXmlExternalEntitiesTest()
        {
            // TODO unit test for the property 'ContainsXmlExternalEntities'
        }
        /// <summary>
        /// Test the property 'ContainsInsecureDeserialization'
        /// </summary>
        [Test]
        public void ContainsInsecureDeserializationTest()
        {
            // TODO unit test for the property 'ContainsInsecureDeserialization'
        }
        /// <summary>
        /// Test the property 'ContainsHtml'
        /// </summary>
        [Test]
        public void ContainsHtmlTest()
        {
            // TODO unit test for the property 'ContainsHtml'
        }
        /// <summary>
        /// Test the property 'ContainsUnsafeArchive'
        /// </summary>
        [Test]
        public void ContainsUnsafeArchiveTest()
        {
            // TODO unit test for the property 'ContainsUnsafeArchive'
        }
        /// <summary>
        /// Test the property 'ContainsOleEmbeddedObject'
        /// </summary>
        [Test]
        public void ContainsOleEmbeddedObjectTest()
        {
            // TODO unit test for the property 'ContainsOleEmbeddedObject'
        }
        /// <summary>
        /// Test the property 'VerifiedFileFormat'
        /// </summary>
        [Test]
        public void VerifiedFileFormatTest()
        {
            // TODO unit test for the property 'VerifiedFileFormat'
        }
        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Test]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }
        /// <summary>
        /// Test the property 'ContentInformation'
        /// </summary>
        [Test]
        public void ContentInformationTest()
        {
            // TODO unit test for the property 'ContentInformation'
        }

    }

}
