/* 
 * virusapi
 *
 * Virus API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Api;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test
{
    /// <summary>
    ///  Class for testing WebsiteScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebsiteScanResultTests
    {
        // TODO uncomment below to declare an instance variable for WebsiteScanResult
        //private WebsiteScanResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebsiteScanResult
            //instance = new WebsiteScanResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebsiteScanResult
        /// </summary>
        [Test]
        public void WebsiteScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebsiteScanResult
            //Assert.IsInstanceOfType<WebsiteScanResult> (instance, "variable 'instance' is a WebsiteScanResult");
        }


        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'WebsiteThreatType'
        /// </summary>
        [Test]
        public void WebsiteThreatTypeTest()
        {
            // TODO unit test for the property 'WebsiteThreatType'
        }

    }

}
