/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VirusScan.Model;
using Cloudmersive.APIClient.NET.VirusScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Model
{
    /// <summary>
    ///  Class for testing WebsiteScanRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebsiteScanRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebsiteScanRequest
        //private WebsiteScanRequest instance;

        public WebsiteScanRequestTests()
        {
            // TODO uncomment below to create an instance of WebsiteScanRequest
            //instance = new WebsiteScanRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebsiteScanRequest
        /// </summary>
        [Fact]
        public void WebsiteScanRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebsiteScanRequest
            //Assert.IsType<WebsiteScanRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
