/*
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NET.VirusScan.Client;
using Cloudmersive.APIClient.NET.VirusScan.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.VirusScan.Model;

namespace Cloudmersive.APIClient.NET.VirusScan.Test.Api
{
    /// <summary>
    ///  Class for testing ScanApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ScanApiTests : IDisposable
    {
        private ScanApi instance;

        public ScanApiTests()
        {
            instance = new ScanApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ScanApi
            //Assert.IsType<ScanApi>(instance);
        }

        /// <summary>
        /// Test ScanFile
        /// </summary>
        [Fact]
        public void ScanFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //var response = instance.ScanFile(inputFile);
            //Assert.IsType<VirusScanResult>(response);
        }

        /// <summary>
        /// Test ScanFileAdvanced
        /// </summary>
        [Fact]
        public void ScanFileAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //string fileName = null;
            //bool? allowExecutables = null;
            //bool? allowInvalidFiles = null;
            //bool? allowScripts = null;
            //bool? allowPasswordProtectedFiles = null;
            //bool? allowMacros = null;
            //bool? allowXmlExternalEntities = null;
            //bool? allowInsecureDeserialization = null;
            //bool? allowHtml = null;
            //bool? allowUnsafeArchives = null;
            //bool? allowOleEmbeddedObject = null;
            //bool? allowUnwantedAction = null;
            //string options = null;
            //string restrictFileTypes = null;
            //var response = instance.ScanFileAdvanced(inputFile, fileName, allowExecutables, allowInvalidFiles, allowScripts, allowPasswordProtectedFiles, allowMacros, allowXmlExternalEntities, allowInsecureDeserialization, allowHtml, allowUnsafeArchives, allowOleEmbeddedObject, allowUnwantedAction, options, restrictFileTypes);
            //Assert.IsType<VirusScanAdvancedResult>(response);
        }

        /// <summary>
        /// Test ScanWebsite
        /// </summary>
        [Fact]
        public void ScanWebsiteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebsiteScanRequest input = null;
            //var response = instance.ScanWebsite(input);
            //Assert.IsType<WebsiteScanResult>(response);
        }
    }
}
